### ISSUE TITLE
Importing Error Into Android Studio

### ISSUE THREAD

**Issue by slidenerd** [OrangeGangsters/CircularBarPager#2]
Yes I already read the issue that you closed about this, I tried what you mentioned there, still doesnt work for me
here is my main gradle file
![snap 2015-02-21 at 15 10 59](https://cloud.githubusercontent.com/assets/5139030/6313618/e88f6862-b9db-11e4-919f-fd338ed31923.png)
This is my app's gradle file
![snap 2015-02-21 at 15 12 02](https://cloud.githubusercontent.com/assets/5139030/6313619/09115c6c-b9dc-11e4-9a88-a0cd1856d343.png)
And this is the error I get
![snap 2015-02-21 at 15 13 10](https://cloud.githubusercontent.com/assets/5139030/6313623/30a973d6-b9dc-11e4-9594-89430dc066b7.png)]
Any help is highly appreciated, thanks,

**Comment by EveryNameTaken** [comment]
Not sure if this is what you need.

Anyway, i add libraries through Project Structure -> Dependencies -> Add and use search from there. I found com.github.orangegangsters:library:1.0.0 which didn't work.

But I also found and tried 'com.github.OrangeGangsters:library:1.0.2', which reported missing viewpagerindicator. I tried to add  'com.viewpagerindicator:parent:2.4.1', didn't work, i need @aar. After   adding 'com.viewpagerindicator:library:2.4.1@aar' i still get same error reporting vivewpager is missing.

After a bit of Googling, you need to add:

        maven { url "http://dl.bintray.com/populov/maven" }
        mavenCentral()

under your repos in build.gradle(Project: bla bla bla :D)

**Comment by slidenerd** [comment]
Big thanks mate @EveryNameTaken  it actually worked! I am closing this issue

**Comment by EveryNameTaken** [comment]
no problem, least I can do to thank you for you great tutorials
