### ISSUE TITLE
Error inflating the view

### ISSUE THREAD

**Issue by lancevalour** [OrangeGangsters/CircularBarPager#4]
Hi,

When I try to use your library, I got the code compiled but got error at runtime. Below is the log:

12-10 16:24:18.671 2561-2561/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 android.view.InflateException: Binary XML file line #14: Error inflating class com.github.OrangeGangsters.circularbarpager.library.CircularBarPager

Can you give me some hints what went wrong? Thanks.

Best,
Yicheng

**Comment by olivierg13** [comment]
Hello @lancevalour 
Did you try to launch the example app and it was not working.
Or did you try integrating this library into your app?

Thank you in advance and sorry for the delay.

Cheers,

Olivier

**Comment by lancevalour** [comment]
Olivier,

Example app works fine.

Error when trying to actually use the library in my app.

I guess there is something wrong with the library hosting. Example code works because it doesn't download library from remote repository.  

Thanks,
Yicheng

**Comment by olivierg13** [comment]
See #2 maybe for your problem?

**Comment by lancevalour** [comment]
No luck here.

So I add mavenCentral() in my build.gradle but nothing changes. 

Yicheng

**Comment by olivierg13** [comment]
I think the important one was to add:
maven { url "http://dl.bintray.com/populov/maven" }

**Comment by lancevalour** [comment]
I add it too. So my build.gradle looks like:

 repositories {
    maven { url "http://dl.bintray.com/populov/maven" }
    mavenCentral()
    jcenter()
}

**Comment by olivierg13** [comment]
Hummm so I don't know why.
Did you try adding 'com.viewpagerindicator:library:2.4.1@aar' to your dependencies? (in the other build.gradle)?

**Comment by lancevalour** [comment]
Yes, I add it.

**Comment by CCorrado** [comment]
I also cannot launch. In XML,
The following classes could not be instantiated:
- com.github.OrangeGangsters.circularbarpager.library.CircularBar (Open Class, Show Exception, Clear Cache)

Looks like that path is incorrect. The code compiles (i am able to reference the Classes in Java)

**Comment by CCorrado** [comment]
For now, I will dump the library locally but I think all you have to do is repackage and upload to maven (or jCenter preferably) Good stuff. Thanks guys!

**Comment by CCorrado** [comment]
http://stackoverflow.com/questions/29615547/cant-add-viewpagerindicator-to-app-with-gradle

Need to make sure the dl.bintray URL is the *first* referenced repo in your list, or else AS gets all pissed about your library not being on jCenter(). This should be resolved :+1:

**Comment by CCorrado** [comment]
Needed the following to get this to work.
compile 'com.github.orangegangsters:library:1.3.4@aar'
    compile 'fr.avianey.com.viewpagerindicator:library:2.4.1.1@aar'
    compile 'com.daimajia.easing:library:1.0.1@aar'
    compile 'com.nineoldandroids:library:2.4.0'
