### ISSUE TITLE
how could this CircularBarPager be used in Fragment?

### ISSUE THREAD

**Issue by caoyl2015** [OrangeGangsters/CircularBarPager#6]
Hi,friend.

When I use CircularBarPager in activity like the sample, it is ok. But when it is used in Fragment, the AndroidStduio logcat shows the message: I/System.out: Binary XML file line #9: Binary XML file line #9: Error inflating class xx.xxx.xxx.xxx.CircleBarPagerLib.CircularBarPager

Thanks Firstly!

**Comment by olivierg13** [comment]
Hello @caoyl2015 
we use it also in Fragment and it's working fine.
Are you sure you're importing the CirucularBarPager fine?
Try to copy paste the whole stacktrace please?

Cheers

**Comment by caoyl2015** [comment]
Thank your reply! I have been working on it for a night. Finaly, I was wrong. Two things should be told.

Firstly,I use this
 "mCircularBarPager = (CircularBarPager) getFragmentManager().findFragmentById(R.id.frag_real).getView().findViewById(R.id.frag_circularBarPager);", 
Now ,I change it to 
"View view = inflater.inflate(R.layout.fragment_realtimemonitor, container, false);
mCircularBarPager = (CircularBarPager) view.findViewById(R.id.frag_circularBarPager);
" in onCreateView for getView().

Secondly, I use the source of viewpagerindicator, I forgot remove the
"compile 'com.viewpagerindicator:library:2.4.1@aar'"  from the build.gradle of library.

When I fix them, It works well.
